### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by rodrigopitanga** [davidgfnet/whatsapp-purple#231]
After pulling and rebuilding whatsapp-purple yesterday I've been unable to start pidgin. I get a segfault as soon as Pidgin receives the first WA message.

Here's the backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209     ../sysdeps/x86_64/multiarch/../strcmp.S: Arquivo ou diretório não encontrado.
(gdb) bt full
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
No locals.
#1  0x00007fffd8d768db in hasht_cmp_id () from /usr/lib/purple-2/libwhatsapp.so
No symbol table info available.
#2  0x00007fffd8d7695d in blist_find_chat_by_hasht_cond () from /usr/lib/purple-2/libwhatsapp.so
No symbol table info available.
#3  0x00007fffd8d777de in get_open_combo () from /usr/lib/purple-2/libwhatsapp.so
No symbol table info available.
#4  0x00007fffd8d77974 in conv_add_message () from /usr/lib/purple-2/libwhatsapp.so
No symbol table info available.
#5  0x00007fffd8d78db7 in waprpl_input_cb () from /usr/lib/purple-2/libwhatsapp.so
No symbol table info available.
#6  0x00005555555c84de in ?? ()
No symbol table info available.
#7  0x00007ffff53aace5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007ffff53ab048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007ffff53ab30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007ffff6633447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#11 0x000055555558f36e in main ()
No symbol table info available.
```

And Pidgin log just before the crash:
```
(17:29:04) whatsapp: Got chat message from 55XXXXXXXXXXX-XXXXXXXXXX: 😂😂😂😂😂
```

**Comment by dequis** [comment]
Can you rebuild it using "make debug" instead of "make"? Then post a new backtrace

**Comment by dequis** [comment]
Nevermind, I can reproduce it:

```
==24540== Invalid read of size 1
==24540==    at 0x4C2D512: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x6142A18: xmlnode_insert_data (xmlnode.c:112)
==24540==    by 0x60C5F55: chat_component_to_xmlnode (blist.c:181)
==24540==    by 0x537823F: g_hash_table_foreach (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x60C6203: chat_to_xmlnode (blist.c:264)
==24540==    by 0x60C62F7: group_to_xmlnode (blist.c:299)
==24540==    by 0x60C6502: blist_to_xmlnode (blist.c:353)
==24540==    by 0x60C65BE: purple_blist_sync (blist.c:382)
==24540==    by 0x60C661C: save_cb (blist.c:392)
==24540==    by 0x53893C2: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5388CF7: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==  Address 0x167c2be0 is 0 bytes inside a block of size 25 free'd
==24540==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x53A87C8: g_strfreev (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0xC9513A7: waprpl_process_incoming_events (wa_purple.c:590)
==24540==    by 0xC951AD7: waprpl_input_cb (wa_purple.c:709)
==24540==    by 0x131B03: gaim_io_invoke (events_glib.c:86)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5388CF7: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5389021: g_main_loop_run (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x131A75: b_main_run (events_glib.c:59)
==24540==    by 0x12F86E: main (unix.c:170)
==24540==
==24540== Invalid read of size 1
==24540==    at 0x4C2D524: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x6142A18: xmlnode_insert_data (xmlnode.c:112)
==24540==    by 0x60C5F55: chat_component_to_xmlnode (blist.c:181)
==24540==    by 0x537823F: g_hash_table_foreach (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x60C6203: chat_to_xmlnode (blist.c:264)
==24540==    by 0x60C62F7: group_to_xmlnode (blist.c:299)
==24540==    by 0x60C6502: blist_to_xmlnode (blist.c:353)
==24540==    by 0x60C65BE: purple_blist_sync (blist.c:382)
==24540==    by 0x60C661C: save_cb (blist.c:392)
==24540==    by 0x53893C2: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5388CF7: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==  Address 0x167c2be1 is 1 bytes inside a block of size 25 free'd
==24540==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x53A87C8: g_strfreev (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0xC9513A7: waprpl_process_incoming_events (wa_purple.c:590)
==24540==    by 0xC951AD7: waprpl_input_cb (wa_purple.c:709)
==24540==    by 0x131B03: gaim_io_invoke (events_glib.c:86)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5388CF7: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5389021: g_main_loop_run (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x131A75: b_main_run (events_glib.c:59)
==24540==    by 0x12F86E: main (unix.c:170)
==24540==
==24540== Invalid read of size 8
==24540==    at 0x4C2ECB0: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x53A6EA5: g_memdup (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x6142A49: xmlnode_insert_data (xmlnode.c:116)
==24540==    by 0x60C5F55: chat_component_to_xmlnode (blist.c:181)
==24540==    by 0x537823F: g_hash_table_foreach (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x60C6203: chat_to_xmlnode (blist.c:264)
==24540==    by 0x60C62F7: group_to_xmlnode (blist.c:299)
==24540==    by 0x60C6502: blist_to_xmlnode (blist.c:353)
==24540==    by 0x60C65BE: purple_blist_sync (blist.c:382)
==24540==    by 0x60C661C: save_cb (blist.c:392)
==24540==    by 0x53893C2: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==  Address 0x167c2be0 is 0 bytes inside a block of size 25 free'd
==24540==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x53A87C8: g_strfreev (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0xC9513A7: waprpl_process_incoming_events (wa_purple.c:590)
==24540==    by 0xC951AD7: waprpl_input_cb (wa_purple.c:709)
==24540==    by 0x131B03: gaim_io_invoke (events_glib.c:86)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5388CF7: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5389021: g_main_loop_run (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x131A75: b_main_run (events_glib.c:59)
==24540==    by 0x12F86E: main (unix.c:170)
==24540==
==24540== Invalid read of size 8
==24540==    at 0x4C2ECBE: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x53A6EA5: g_memdup (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x6142A49: xmlnode_insert_data (xmlnode.c:116)
==24540==    by 0x60C5F55: chat_component_to_xmlnode (blist.c:181)
==24540==    by 0x537823F: g_hash_table_foreach (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x60C6203: chat_to_xmlnode (blist.c:264)
==24540==    by 0x60C62F7: group_to_xmlnode (blist.c:299)
==24540==    by 0x60C6502: blist_to_xmlnode (blist.c:353)
==24540==    by 0x60C65BE: purple_blist_sync (blist.c:382)
==24540==    by 0x60C661C: save_cb (blist.c:392)
==24540==    by 0x53893C2: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==  Address 0x167c2bf0 is 16 bytes inside a block of size 25 free'd
==24540==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24540==    by 0x53A87C8: g_strfreev (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0xC9513A7: waprpl_process_incoming_events (wa_purple.c:590)
==24540==    by 0xC951AD7: waprpl_input_cb (wa_purple.c:709)
==24540==    by 0x131B03: gaim_io_invoke (events_glib.c:86)
==24540==    by 0x538891C: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5388CF7: ??? (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x5389021: g_main_loop_run (in /usr/lib/libglib-2.0.so.0.4200.1)
==24540==    by 0x131A75: b_main_run (events_glib.c:59)
==24540==    by 0x12F86E: main (unix.c:170)
==24540==
```

Introduced by the last commit (if you want a workaround, do `git checkout b2ea6bf`)

**Comment by rodrigopitanga** [comment]
> Introduced by the last commit (if you want a workaround, do `git checkout b2ea6bf`)

still crashing.

```
#4  0x00007fffd8d61b24 in get_open_combo (who=0x555558fdb160 "5511984573879-1398042565", gc=0x555558ac3710) at wa_purple.c:366
        convo = 0x555558c032d0
        ch = 0x0
        hasht = 0x7fffd8d616ad <isgroup+29>
        convo_id = 32767
        groupname = 0x6 <error: N�o � poss�vel acessar a mem�ria no endere�o 0x6>
        acc = 0x555555966430
```

Got a backgrace with wa_purple debug symbols. This `groupname = 0x6` looks strange.

**Comment by rodrigopitanga** [comment]
> Introduced by the last commit (if you want a workaround, do `git checkout b2ea6bf`)

still crashing. 

``` #4 0x00007fffd8d61b24 in get_open_combo (who=0x555558fdb160 "5511984573879-1398042565", gc=0x555558ac3710) at wa_purple.c:366 convo = 0x555558c032d0 ch = 0x0 hasht = 0x7fffd8d616ad <isgroup+29> convo_id = 32767 groupname = 0x6 <error: Não é possível acessar a memória no endereço 0x6> acc = 0x555555966430 ``` Got a backgrace with wa_purple debug symbols. This `groupname = 0x6` looks strange.

**Comment by dequis** [comment]
Uhm, that's just frame 4. What about the rest?

And yeah now i see the errors are different.

Line 366 is three lines above the declaration `groupname`, don't expect it to have a meaningful value.

**Comment by dequis** [comment]
Okay upon closer inspection, I'm guessing this is some groupchat with a NULL "id". The full backtrace wasn't really needed (and that frame 4 helps confirm a few things)

This would confirm it:

```
(gdb) frame 1
(gdb) p g_hash_table_lookup(hasht, "id")
```

@davidgfnet Using `g_strcmp0` instead of `strcmp` in `hasht_cmp_id` would be a quick workaround for this, but how the hell does a null get in there in the first place? *worry*

**Comment by davidgfnet** [comment]
Ops... So it seems that "blist_find_chat_by_id" is being called with a non-existing group id? How can I reproduce it? I hasn't happened to me and I've been chatting for two days on HEAD.
A backtrace with symbols would be nice (or .so + coredump). Thanks guys!

**Comment by davidgfnet** [comment]
Can you try again with HEAD? I fixed a bug there. But I'm not confident since you say that reverting that commit did not work at all.

**Comment by davidgfnet** [comment]
Can you check on HEAD again please? Thanks!!

**Comment by rodrigopitanga** [comment]
```
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
No locals.
#1  0x00007fffd8d61978 in hasht_cmp_id (hasht=0x5555568b5060, data=0x7fffffff7600) at wa_purple.c:330
No locals.
#2  0x00007fffd8d61915 in blist_find_chat_by_hasht_cond (gc=0x555558ac7d60, fn=0x7fffd8d61942 <hasht_cmp_id>, data=0x7fffffff7600) at wa_purple.c:318
        ch = 0x5555568b5df0
        account = 0x555555966460
        node = 0x5555568b5df0
        hasht = 0x5555568b5060
#3  0x00007fffd8d619e9 in blist_find_chat_by_id (gc=0x555558ac7d60, id=0x555558e9c550 "5511975472525-1343781223") at wa_purple.c:340
No locals.
#4  0x00007fffd8d61cdc in get_open_combo (who=0x555558e9c550 "5511975472525-1343781223", gc=0x555558ac7d60) at wa_purple.c:392
        convo = 0x0
        ch = 0x555558f5e8d0
        hasht = 0x5555558d4040
        convo_id = 32767
        groupname = 0x555558e9c550 "xxxxx"
        acc = 0x555555966460
        wconn = 0x555558ac7ea0
#5  0x00007fffd8d61ece in conv_add_message (gc=0x555558ac7d60, who=0x555558e9c550 "5511975472525-1343781223", msg=0x555558f5e8d0 "xxxxx", 
    author=0x555558f61df0 "5511970942529", timestamp=1425552660) at wa_purple.c:429
        convo = 0x555558ca9d90
#6  0x00007fffd8d628d6 in waprpl_process_incoming_events (gc=0x555558ac7d60) at wa_purple.c:618
        wconn = 0x555558ac7ea0
        acc = 0x555555966460
        err = 0
        m = {type = 0, who = 0x555558e9c550 "xxxxx", message = 0x555558f5e8d0 "xxxxx", author = 0x555558f61df0 "xxxxx", 
          t = 1425552660, image = 0x0, imagelen = 0, url = 0x0, lat = 0, lng = 0}
#7  0x00007fffd8d6302e in waprpl_input_cb (data=0x555558ac7d60, source=30, cond=PURPLE_INPUT_READ) at wa_purple.c:728
        gc = 0x555558ac7d60
        wconn = 0x555558ac7ea0
        tempbuff = "|\224\341\323\066e\nH\252p|\203\323\023\277W\261\371\323\346'\337y}݆V\230\307غ\361\261\336\001\304\365\270\350Ш4d\373\262R\207\021,\260\061Iٿ0\203ɷ/',\212\304Ў\325\032Z\224\316H\363\325fø߷Qٸ\322ןzJ\367V\245\342=?ؑӭ\026\364\375OP\350\061\250\230\063s\364\363\366Z\203٢ntHeA\211\067Z\210\060\060\334Ғ\001o\221\343&P\233\f\aR\303H#Q\266\254\016aNDD\004\214\323\031\340+mԴIq\325\347\271/\342\v\237\357i\227\274\327>K\316i\232}~\320\334#5\221\a>5\210\070\003\227}\250\"!\344@\\\217\005\272\312\354^\243\365WR2iv\263#JM"...
        ret = -1
#8  0x00005555555c84de in ?? ()
No symbol table info available.
#9  0x00007ffff53aace5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007ffff53ab048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#11 0x00007ffff53ab30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#12 0x00007ffff6633447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#13 0x000055555558f36e in main ()
No symbol table info available.
```

Still crashes on `HEAD`.

Here's one of my chats in `blist.xml`:

			<chat proto='prpl-whatsapp' account='xxxx'>
				<alias>xxx</alias>
				<component name='id'>xxxxx</component>
				<component name='owner'>xxxx</component>
				<component name='subject'>xxxx</component>
				<setting name='gtk-mute-sound' type='bool'>0</setting>
			</chat>

**Comment by davidgfnet** [comment]
Could you also paste the debug log (all of it please). I know it's a pain
in the ass to anonymize it, so maybe you want to send it to me over email.

Thanks!

**Comment by rodrigopitanga** [comment]
Also tried to disable the offending group commenting it out of blist.xml, but still crashes. I've also noticed that this is not specific to any group.

**Comment by rodrigopitanga** [comment]
@davidgfnet Full log sent.

**Comment by dequis** [comment]
@davidgfnet Sup?

**Comment by dequis** [comment]
soooo what happened with this one?

**Comment by davidgfnet** [comment]
Totally forgot. I don't know seems weird, only one person having this error? Seems a config problem to me. Otherwise there would be hordes of people complaining.

**Comment by dequis** [comment]
Nothing interesting in the debug log either?

**Comment by rodrigopitanga** [comment]
I may have solved the problem. **tl,dr;** removed all my chats from blist.xml and restarted. Fine. But the problem goes deeper.

Apparently `g_hash_table_lookup()` in `hasht_cmp_id()` was returning null and being used as an argument to a `strcmp()`. But `strcmp()` has an undefined behavior for null arguments, hence the segfault. It would be a good thing to sanity-check the arguments before doing a strcmp anyway. I did that and the segfault appeared somewhere else.

Now, why is `g_hash_table_lookup()` returning null? Did my blist.xml get corrupted?

**Comment by dequis** [comment]
Yep, so, back to what i said before:

>Using `g_strcmp0` instead of `strcmp` in `hasht_cmp_id` would be a quick workaround for this, but how the hell does a null get in there in the first place? *worry*

I vote going for the g_strcmp0 "solution" (and forget about it)
